### PR TITLE
[MRG] MAINT: setup file contd

### PR DESCRIPTION
**Pull request by jasmainak**
work in progress still ... don't merge, just declaring my intention :)

### CODE REVIEW

**Comment by juangpc** [comment]
Oops! Tried to merge too soon. See your comment now. OK.

**Comment by jasmainak** [comment]
@juangpc can you merge and try the instructions that I added now. I think it's easier than what was recommended before for installation?

**Comment by jasmainak** [comment]
Also, I think we should take this script out of the folder :

https://github.com/juangpc/fieldline-opm-client/blob/main/fieldline_client/mne_fieldline.py

remove the shell script and use this instead:

https://setuptools.readthedocs.io/en/latest/userguide/entry_point.html

I can do it in a follow up PR if you're open to the idea :)

**Comment by juangpc** [comment]
Hi @jasmainak, 
Both windows10 and centos8 fail. environment is created and activated correctly. But when running pip install... 

```
ERROR: Could not find a version that satisfies the requirement fieldline_api (from fieldline-client) (from versions: none)
ERROR: No matching distribution found for fieldline_api

```

...Is there something I'm doing wrong?


image

**Comment by jasmainak** [comment]
indeed, I can reproduce on CentOS. I'll take a look tomorrow (Thu)

**Pull request merged**
